### ISSUE TITLE
Major issue after Upgrade to 13.0.1 - 

### ISSUE THREAD

**Issue by randomnickname1337** [newroco/W2G2#21]
Upgraded from 12.0.5 to 13.0.1 
after upgrade , when i go to aditional settings i get Internal server error.
Here is nextcloud log. It causes error for users which are using lock feature. After login , they are getting Internal error too.

I love your app and appreciate your work , but atm app is not working. tried remove and install , still same. It looks for me like compatibility problem.

> .Doctrine\DBAL\Exception\SyntaxErrorException: An exception occurred while executing 'ALTER TABLE oc_locks_w2g2 RENAME COLUMN name TO file_id': SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'COLUMN name TO file_id' at line 1

    /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php - line 128: Doctrine\DBAL\Driver\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\DBAL\Driver\PDOException))
    /var/www/html/nextcloud/3rdparty/doctrine/dbal/lib/Doctrine/DBAL/Statement.php - line 177: Doctrine\DBAL\DBALException driverExceptionDuringQuery(Object(Doctrine\DBAL\Driver\PDOMySql\Driver), Object(Doctrine\DBAL\Driver\PDOException), 'ALTER TABLE oc_...', Array)
    /var/www/html/nextcloud/lib/private/legacy/db/statementwrapper.php - line 73: Doctrine\DBAL\Statement->execute()
    /var/www/html/nextcloud/apps/w2g2/lib/Migration/UpdateDatabase.php - line 87: OC_DB_StatementWrapper->execute()
    /var/www/html/nextcloud/apps/w2g2/lib/Migration/UpdateDatabase.php - line 20: OCA\w2g2\Migration\UpdateDatabase->update()
    /var/www/html/nextcloud/apps/w2g2/ajax/updateDatabase.php - line 14: OCA\w2g2\Migration\UpdateDatabase->run()
    /var/www/html/nextcloud/lib/private/Route/Route.php - line 155: require_once('/var/www/html/n...')
    [internal function] OC\Route\Route->OC\Route\{closure}(*** sensitive parameters replaced ***)
    /var/www/html/nextcloud/lib/private/Route/Router.php - line 297: call_user_func(Object(Closure), Array)
    /var/www/html/nextcloud/lib/base.php - line 998: OC\Route\Router->match('/apps/w2g2/ajax...')
    /var/www/html/nextcloud/index.php - line 37: OC handleRequest()
    {main}

**Comment by orzuionut** [comment]
We've released a new version that should fix this. Please update

**Comment by Shinrai** [comment]
See Issue #26 as to why it was failing and why it's still not fixed.
